// client/src/app/app.component.ts
import { Component, OnInit, inject } from "@angular/core";
import { UserService } from "./services/user.service";
import { MatToolbar } from "@angular/material/toolbar";
import { RouterOutlet } from "@angular/router";

@Component({
    selector: "app-root",
    templateUrl: "./app.component.html",
    styleUrls: ["./app.component.scss"],
    imports: [MatToolbar, RouterOutlet]
})
export class AppComponent implements OnInit {
  private readonly usr = inject(UserService);


  ngOnInit(): void {

    // load/apply user prefs
    this.usr.loadSettings();
  }
}

<mat-toolbar class="noselect main-toolbar" color="default">
  <div>
    <h1 class="no-wrap">
      <a href="https://github.com/facioquo/stock-charts" target="_blank" rel="noopener">
        stock chart
      </a>
    </h1>
    <h2>
      <a href="https://dotnet.stockindicators.dev" target="_blank" rel="noopener">
        <strong>Stock Indicators for .NET</strong>
      </a>
    </h2>
  </div>
</mat-toolbar>

<main id="main-content" class="content-container">

  <div class="button-container">
    <button mat-fab color="accent" *ngIf="!cht.loading" (click)="openSettingsDialog()"
      matTooltip="change indicators and settings" aria-label="change indicators and settings">
      <mat-icon color="primary">edit</mat-icon>
    </button>
  </div>

  <app-chart></app-chart>
</main>

// web/src/components/App.tsx
import { useEffect } from "react";
import { Outlet } from "react-router-dom";

import { loadSettings } from "../services/userPrefs";

/**
 * Root shell — header toolbar + routed outlet. Ports `AppComponent`, applying
 * saved user preferences (theme) on mount.
 */
export function App(): React.JSX.Element {
  useEffect(() => {
    loadSettings();
  }, []);

  return (
    <>
      <header>
        <div className="main-toolbar noselect">
          <div>
            <h1 className="no-wrap">
              <a href="https://dotnet.stockindicators.dev" target="_blank" rel="noopener">
                stock indicators <small>for .NET</small>
              </a>
            </h1>
            <h2 className="no-wrap">
              <a
                href="https://github.com/facioquo/stock-charts"
                target="_blank"
                rel="noopener noreferrer"
              >
                <strong>demo site</strong>
              </a>
            </h2>
          </div>
        </div>
      </header>

      <main id="main-content">
        <Outlet />
      </main>
    </>
  );
}
